### ISSUE TITLE
Add configuration ability

### ISSUE THREAD

**Issue by Valve** [seatgeek/sixpack-rb#11]
To be able to configure the sixpack-rb once (let's say in a rails initializer) and don't provide the basic options with every session initialization. Session options should override configuration options though.
Session options should also be usable alone, when no configuration block is used.

Please let me know if you want a PR for this

**Comment by zackkitzmiller** [comment]
This seems like a pretty reasonable change to me. We just want to make sure we don't introduce a Rails dependancy.

**Comment by Valve** [comment]
Fixed in https://github.com/seatgeek/sixpack-rb/pull/19
