### ISSUE TITLE
Fix deprecated RSpec syntax

### ISSUE THREAD

**Issue by Valve** [seatgeek/sixpack-rb#13]
It's using pre 3.0 syntax (should), which is a global monkey patch and a bad thing overall.
Use newer expect matchers

**Comment by zackkitzmiller** [comment]
This is another one of those things that would be super helpful in a PR. :)

**Comment by Valve** [comment]
Yeah, will do tomorrow

**Comment by Valve** [comment]
Fixed in https://github.com/seatgeek/sixpack-rb/pull/19
