### ISSUE TITLE
Gem version

### ISSUE THREAD

**Issue by dougdroper** [seatgeek/sixpack-rb#18]
Is it possible to cut a new version of this gem please?

**Comment by zackkitzmiller** [comment]
Done

**Comment by dougdroper** [comment]
@zackkitzmiller thanks very much, there seems to be some inconsistency between https://rubygems.org/gems/sixpack-client which says v 1.2.0 as the latest, and https://github.com/seatgeek/sixpack-rb/blob/master/lib/sixpack/version.rb which is on 1.1.0
