### ISSUE TITLE
New version bump?

### ISSUE THREAD

**Issue by valo** [seatgeek/sixpack-rb#24]
I just noticed that the kpi changes[1] are not included in the latest gem version. Do you have plans to release a new version to rubygems soon?

[1] https://github.com/seatgeek/sixpack-rb/pull/21

**Comment by zackkitzmiller** [comment]
Absolutely. I can do this later today/early tomorrow.

**Comment by valo** [comment]
Wow! Thanks for the fast response :+1:

**Comment by zackkitzmiller** [comment]
Figured I'd just do this now and push v1.3.0 to rubygems. You're all set.
