### ISSUE TITLE
Why capitalized alternatives are bad

### ISSUE THREAD

**Issue by Valve** [seatgeek/sixpack-rb#5]
When I try using capitalized alternatives (['Alt1', 'Alt2']), the client throws an exception: Bad alternative name.

Two issues here.

1. This is a very bad error message. It does not say why the alternative name is bad, one is forced to find this place in the source code to figure it out.
2. Why are capitalized alternative names prohibited? What's the motivation behind this?

Please let me know if you'd submit a PR fixing this.

**Comment by zackkitzmiller** [comment]
You're correct, the exception thrown isn't great. I'd gladly accept a PR. The motivation is to avoid accidental errors. 

i.e. You participate the test with `Alt1`, but accidentally convert with `alt1`.

**Comment by Valve** [comment]
Fixed in https://github.com/seatgeek/sixpack-rb/commit/c48842111563a7033e0e1822fa0918585025fa49
