### ISSUE TITLE
Basic authentication

### ISSUE THREAD

**Issue by Valve** [seatgeek/sixpack-rb#7]
Please add it

**Comment by zackkitzmiller** [comment]
I'm not quite sure what you mean. There is no authorization layer on sixpack server, so there is no client component. I'd assume you'd probably just want to lock down traffic from your web server to the sixpack server with Security Groups, or whatever firewall solution you use.

**Comment by Valve** [comment]
For example I'm using sixpack + gunicorn behind a nginx and have a basic auth on nginx. How should I connect to it in this case?
I'm curious because of the scenario with dynamic IPs (like auto provisioned servers)

**Comment by zackkitzmiller** [comment]
With auto-provisioned servers I would assume that you have a DNS entry for something like `sixpack.yourdomain.com`. I'd probably avoid using basic auth with sixpack because it's going to increase connection time. You could, however, put your basic auth in the URL: `https://gooduser:secretpassword@www.example.com/sixpack`

**Comment by Valve** [comment]
Thanks

**Comment by Valve** [comment]
Just to add more details to this conversation, here is the relevant part from the Heroku documentation:
>> Because the Heroku dyno grid is dynamic in nature, the IP address that a given dyno will be assigned over time will be both dynamic and unpredictable. This dynamic sourcing of outbound traffic can make it difficult to integrate with APIs or make connections through firewalls that require IP-based whitelisting.

So this will require either basic auth on a proxy server or a token-based authentication inside sixpack.
